name: Build App

on:
  push:
    branches:
      - '*'

jobs:
  generate:
    name: Generate Quran Images
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Docker
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docker-desktop -y

      - name: Generate Images
        run: |
          docker-compose up -d
          docker-compose run gen /app/script/generate.pl --output ./output/ ...
          docker-compose run gen zopflipng --prefix=comp/ ... ./output/*.png
          docker-compose stop

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: QuranImages
          path: output
