name: Build App

on:
  push:
    branches:
      - '*'

jobs:
  generate:
    name: Generate Quran Images
    runs-on: windows-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install MySQL
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install mysql -y

      - name: Install ActivePerl
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install activeperl -y

      - name: Install Make
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install make -y

      - name: Install Required Packages
        run: |
          ppm install dmake
          ppm install dbd-mysql
          ppm install yaml

      - name: Generate Images
        run: |
          perl Makefile.PL
          make
          make install
          net start mysql
          mysql -u root < sql/schema.sql
          mysql -u root < sql/database.sql
          mysql -u root -e "create user 'nextgen'@'localhost' identified by 'nextgen'"
          mysql -u root -e "grant all privileges on nextgen.* to 'nextgen'@'localhost'"
          mysql -u root -e "flush privileges"
          ./script/generate.pl --width 1300 --output ./output/ --pages 1..604

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: QuranImages
          path: output
