name: Build App

on:
  push:
    branches:
      - '*'

jobs:
  generate:
    name: Generate Quran Images
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v2

      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800
          container port: 3307
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'nextgen'
          mysql root password: 'your_password'
          mysql user: 'nextgen'
          mysql password: 'nextgen'


      - name: Generate Images
        run: |
          sudo apt-get update -qq && \
          sudo apt-get install -y \
          libgd-gd2-perl libgd-text-perl \
          libdbd-mysql-perl libdbi-perl \
          libconfig-yaml-perl \
          make gcc g++ \
          unzip \
          mysql-server \
          curl && \
          sudo apt-get clean && \
          sudo rm -rf /var/lib/apt/lists/* && \
          sudo perl Makefile.PL && \
          sudo make && \
          sudo make install && \
          sudo curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious && \
          sudo cpan install Mojo::Log && \
          sudo systemctl start mysql
          sudo mysql -u root -p your_password < sql/01-schema.sql
          sudo mysql -u root -p your_password < sql/02-database.sql
          sudo mysql -u root -p your_password < sql/03-basmallah-shaddah.sql
          sudo mysql -u root -p your_password -e "create user 'nextgen'@'localhost' identified by 'nextgen'"
          sudo mysql -u root -p your_password -e "grant all privileges on nextgen.* to 'nextgen'@'localhost'"
          sudo mysql -u root -p your_password -e "flush privileges"
          ./script/generate.pl --width 1280 --output ./output/ --pages 1..604

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: QuranImages
          path: output
