name: Build App

on:
  push:
    branches:
      - '*'

jobs:
  generate:
    name: Generate Quran Images
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Generate Images
        run: |
          apt-get install -y \
          libgd-gd2-perl libgd-text-perl \
          libdbd-mysql-perl libdbi-perl \
          libconfig-yaml-perl \
          make gcc g++ \
          unzip \
          curl && \
          apt-get clean && \
          rm -rf /var/lib/apt/lists/*
          perl Makefile.PL && \
          make && \
          make install && \
          curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious
          ./script/generate.pl --width 1280 --output ./output/ --pages 1..604

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: QuranImages
          path: output
